// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dock from "./Dock.res.mjs";
import * as Tabs from "../../ui/Tabs.res.mjs";
import * as Hooks from "../../hooks/Hooks.res.mjs";
import * as Utils from "../../Utils.res.mjs";
import * as React from "react";
import * as Slider from "../../ui/Slider.res.mjs";
import * as Spinner from "../../ui/Spinner.res.mjs";
import * as Timeline from "./Timeline/Timeline.res.mjs";
import * as ChunksList from "./ChunksList/ChunksList.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as StyleEditor from "./StyleEditor/StyleEditor.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as EditorCanvas from "./EditorCanvas.res.mjs";
import * as EditorContext from "./EditorContext.res.mjs";
import * as UseEditorLayout from "../../hooks/useEditorLayout.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SubtitleOctopusPreview from "./SubtitleOctopusPreview.res.mjs";

function a(prim) {
  return {};
}

console.log("Happy subtitles making experience!");

function useIsMobile() {
  var match = React.useState(function () {
        return window.innerWidth < 768;
      });
  var setIsMobile = match[1];
  React.useEffect((function () {
          var handleResize = function (param) {
            setIsMobile(function (param) {
                  return window.innerWidth < 768;
                });
          };
          window.addEventListener("resize", handleResize);
          return (function () {
                    window.removeEventListener("resize", handleResize);
                  });
        }), []);
  return match[0];
}

function calcMobilePreviewScale(videoWidth, videoHeight) {
  var vw = window.innerWidth - 24.0;
  var vh = window.innerHeight * 0.45;
  return Math.min(vw / videoWidth, vh / videoHeight);
}

function Editor$MobileSeekSlider(props) {
  var duration = props.duration;
  var ctx = EditorContext.useEditorContext();
  var match = ctx.usePlayer();
  var playerDispatch = match[1];
  var player = match[0];
  var handleSeek = Hooks.useEvent(function (value) {
        playerDispatch({
              TAG: "Seek",
              _0: value
            });
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Slider.make, {
                      onValueChange: handleSeek,
                      disabled: false,
                      value: player.ts | 0,
                      min: 0,
                      max: duration | 0,
                      step: 1
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("span", {
                              children: Utils.Duration.formatSeconds(player.ts)
                            }),
                        JsxRuntime.jsx("span", {
                              children: Utils.Duration.formatSeconds(duration)
                            })
                      ],
                      className: "flex justify-between text-xs text-zinc-400 mt-1"
                    })
              ],
              className: "w-full px-4 py-2"
            });
}

var MobileSeekSlider = {
  make: Editor$MobileSeekSlider
};

function make(width, height, scale) {
  return {
          height: height.toString() + "px",
          width: width.toString() + "px",
          transform: "scale(" + scale.toString() + ")",
          transformOrigin: "top left"
        };
}

var MobileCanvasStyle = {
  make: make
};

function Editor$SaveStatusBadge(props) {
  var match;
  switch (props.saveStatus) {
    case "error" :
        match = [
          "Save failed",
          "text-red-400"
        ];
        break;
    case "saved" :
        match = [
          "Saved",
          "text-green-400"
        ];
        break;
    case "saving" :
        match = [
          "Saving…",
          "text-zinc-400"
        ];
        break;
    default:
      match = [
        "",
        ""
      ];
  }
  var label = match[0];
  if (label.length === 0) {
    return null;
  } else {
    return JsxRuntime.jsx("span", {
                children: label,
                className: "text-xs font-medium " + match[1]
              });
  }
}

var SaveStatusBadge = {
  make: Editor$SaveStatusBadge
};

var make$1 = React.memo(function (props) {
      var onBack = props.onBack;
      var onResetPlayerState = props.onResetPlayerState;
      var videoFileName = props.videoFileName;
      var renderCanvasKey = props.renderCanvasKey;
      var rendererPreviewCanvasRef = props.rendererPreviewCanvasRef;
      var render = props.render;
      var subtitlesManager = props.subtitlesManager;
      var match = Hooks.useToggle(false);
      var fullScreenToggler = match[1];
      var ctx = EditorContext.useEditorContext();
      Hooks.useEditorLayout(match[0]);
      var isMobile = useIsMobile();
      var viewportSize = Hooks.useDimensions();
      var videoWidth = ctx.videoMeta.width;
      var videoHeight = ctx.videoMeta.height;
      React.useEffect((function () {
              onResetPlayerState(function () {
                    ctx.playerImmediateDispatch("AbortRender");
                  });
            }), []);
      var transcriptionInProgress = subtitlesManager.transcriptionState === "TranscriptionInProgress";
      var subtitlesTitle = transcriptionInProgress ? JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Spinner.make, {}),
                JsxRuntime.jsx("span", {
                      children: "Transcribing"
                    })
              ],
              className: "gap-2 inline-flex items-center"
            }) : "Subtitles";
      var lastIsTranscriptionInProgress = React.useRef(transcriptionInProgress);
      React.useLayoutEffect((function () {
              if (!transcriptionInProgress && lastIsTranscriptionInProgress.current) {
                lastIsTranscriptionInProgress.current = true;
                ctx.playerImmediateDispatch("UpdateCurrentCue");
              }
              
            }), [subtitlesManager.transcriptionState]);
      var styleTitle = "Style";
      var match$1 = React.useState(function () {
            return calcMobilePreviewScale(videoWidth, videoHeight);
          });
      var setMobileScale = match$1[1];
      var mobileScale = match$1[0];
      React.useEffect((function () {
              var onResize = function (param) {
                setMobileScale(function (param) {
                      return calcMobilePreviewScale(videoWidth, videoHeight);
                    });
              };
              window.addEventListener("resize", onResize);
              return (function () {
                        window.removeEventListener("resize", onResize);
                      });
            }), []);
      var mobileCanvasStyle = make(ctx.videoMeta.width, ctx.videoMeta.height, mobileScale);
      var mobilePreviewContent = JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("canvas", {
                                  ref: Caml_option.some(ctx.dom.canvasRef),
                                  className: "bg-black absolute inset-0",
                                  id: "editor-preview",
                                  style: mobileCanvasStyle,
                                  height: ctx.videoMeta.height.toString(),
                                  width: ctx.videoMeta.width.toString()
                                }),
                            JsxRuntime.jsx("canvas", {
                                  ref: Caml_option.some(rendererPreviewCanvasRef),
                                  className: "absolute inset-0",
                                  style: mobileCanvasStyle,
                                  height: ctx.videoMeta.height.toString(),
                                  width: ctx.videoMeta.width.toString()
                                }, renderCanvasKey.toString()),
                            JsxRuntime.jsx(SubtitleOctopusPreview.make, {
                                  cues: subtitlesManager.activeSubtitles
                                }),
                            JsxRuntime.jsx(EditorCanvas.make, {
                                  transcriptionInProgress: transcriptionInProgress,
                                  width: ctx.videoMeta.width,
                                  height: ctx.videoMeta.height,
                                  style: mobileCanvasStyle,
                                  className: "absolute inset-0",
                                  subtitles: subtitlesManager.activeSubtitles,
                                  subtitlesManager: subtitlesManager
                                })
                          ],
                          className: "relative shrink-0",
                          style: {
                            height: (videoHeight * mobileScale).toString() + "px",
                            width: (videoWidth * mobileScale).toString() + "px"
                          }
                        }),
                    className: "flex-1 flex items-center justify-center min-h-0"
                  }),
              JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx(Editor$MobileSeekSlider, {
                          duration: ctx.videoMeta.duration
                        }),
                    className: "shrink-0 bg-zinc-900/80 backdrop-blur-sm rounded-lg mx-3 mb-2 p-1"
                  })
            ],
            className: "flex flex-col h-full overflow-hidden"
          });
      var header = JsxRuntime.jsxs("header", {
            children: [
              JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("svg", {
                            children: JsxRuntime.jsx("path", {
                                  d: "M15 19l-7-7 7-7",
                                  strokeLinecap: "round",
                                  strokeLinejoin: "round"
                                }),
                            className: "h-4 w-4",
                            fill: "none",
                            stroke: "currentColor",
                            strokeWidth: "2",
                            viewBox: "0 0 24 24"
                          }),
                      "Back"
                    ],
                    className: "flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-sm text-zinc-400 transition-colors hover:bg-zinc-800 hover:text-white",
                    onClick: (function (param) {
                        onBack();
                      })
                  }),
              JsxRuntime.jsx("span", {
                    className: "h-4 w-px bg-zinc-700"
                  }),
              JsxRuntime.jsx("p", {
                    children: props.projectTitle,
                    className: "flex-1 truncate text-sm font-medium text-white"
                  }),
              JsxRuntime.jsx(Editor$SaveStatusBadge, {
                    saveStatus: props.saveStatus
                  })
            ],
            className: "shrink-0 flex items-center gap-3 px-3 py-2 border-b border-zinc-800 bg-zinc-950/90 backdrop-blur-sm"
          });
      if (isMobile) {
        return JsxRuntime.jsxs("div", {
                    children: [
                      header,
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(Tabs.make, {
                                  tabs: [
                                    {
                                      id: "subtitles",
                                      name: subtitlesTitle,
                                      content: JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx(ChunksList.make, {
                                                  subtitlesManager: subtitlesManager,
                                                  title: null
                                                }),
                                            className: "px-3 py-2"
                                          })
                                    },
                                    {
                                      id: "style",
                                      name: styleTitle,
                                      content: JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx(StyleEditor.make, {}),
                                            className: "px-3 py-2"
                                          })
                                    },
                                    {
                                      id: "preview",
                                      name: "Preview",
                                      content: mobilePreviewContent
                                    }
                                  ],
                                  defaultIndex: 0,
                                  className: "outline-none"
                                }),
                            className: "flex-1 flex flex-col min-h-0"
                          }),
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx(Dock.make, {
                                  subtitlesManager: subtitlesManager,
                                  render: render,
                                  fullScreenToggler: fullScreenToggler,
                                  videoFileName: videoFileName,
                                  projectId: props.projectId
                                }),
                            className: "shrink-0 border-t border-zinc-800 bg-zinc-900/95 backdrop-blur-sm flex justify-center py-1"
                          })
                    ],
                    className: "w-screen h-dvh bg-zinc-950 flex flex-col fixed inset-0 overflow-hidden",
                    id: "fframes-editor"
                  });
      }
      var rightPanelViewport_width = viewportSize.width - 460 | 0;
      var rightPanelViewport_height = viewportSize.height;
      var rightPanelViewport = {
        width: rightPanelViewport_width,
        height: rightPanelViewport_height
      };
      var desktopPreview = UseEditorLayout.calculatePreviewSize(rightPanelViewport, ctx.videoMeta, 0, UseEditorLayout.min_timeline_height);
      return JsxRuntime.jsxs("div", {
                  children: [
                    header,
                    JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsx(Tabs.make, {
                                        tabs: [
                                          {
                                            id: "subtitles",
                                            name: subtitlesTitle,
                                            content: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx(ChunksList.make, {
                                                        subtitlesManager: subtitlesManager,
                                                        title: null
                                                      }),
                                                  className: "px-4 py-3 h-full"
                                                })
                                          },
                                          {
                                            id: "style",
                                            name: styleTitle,
                                            content: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx(StyleEditor.make, {}),
                                                  className: "px-4 py-3"
                                                })
                                          }
                                        ],
                                        defaultIndex: 0,
                                        className: "outline-none"
                                      }),
                                  className: "w-[460px] shrink-0 flex flex-col border-r border-zinc-800 overflow-hidden bg-zinc-950"
                                }),
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("canvas", {
                                                        ref: Caml_option.some(ctx.dom.canvasRef),
                                                        className: "bg-black absolute inset-0",
                                                        id: "editor-preview",
                                                        style: {
                                                          height: ctx.videoMeta.height.toString() + "px",
                                                          width: ctx.videoMeta.width.toString() + "px",
                                                          transform: "scale(" + desktopPreview.scale.toString() + ")",
                                                          transformOrigin: "top left"
                                                        },
                                                        height: ctx.videoMeta.height.toString(),
                                                        width: ctx.videoMeta.width.toString()
                                                      }),
                                                  JsxRuntime.jsx("canvas", {
                                                        ref: Caml_option.some(rendererPreviewCanvasRef),
                                                        className: "absolute inset-0",
                                                        style: {
                                                          height: ctx.videoMeta.height.toString() + "px",
                                                          width: ctx.videoMeta.width.toString() + "px",
                                                          transform: "scale(" + desktopPreview.scale.toString() + ")",
                                                          transformOrigin: "top left"
                                                        },
                                                        height: ctx.videoMeta.height.toString(),
                                                        width: ctx.videoMeta.width.toString()
                                                      }, renderCanvasKey.toString()),
                                                  JsxRuntime.jsx(SubtitleOctopusPreview.make, {
                                                        cues: subtitlesManager.activeSubtitles
                                                      }),
                                                  JsxRuntime.jsx(EditorCanvas.make, {
                                                        transcriptionInProgress: transcriptionInProgress,
                                                        width: ctx.videoMeta.width,
                                                        height: ctx.videoMeta.height,
                                                        style: {
                                                          height: ctx.videoMeta.height.toString() + "px",
                                                          width: ctx.videoMeta.width.toString() + "px",
                                                          transform: "scale(" + desktopPreview.scale.toString() + ")",
                                                          transformOrigin: "top left"
                                                        },
                                                        className: "bg-transparent absolute inset-0",
                                                        subtitles: subtitlesManager.activeSubtitles,
                                                        subtitlesManager: subtitlesManager
                                                      })
                                                ],
                                                className: "relative shrink-0 bg-black",
                                                style: {
                                                  height: (ctx.videoMeta.height * desktopPreview.scale).toString() + "px",
                                                  width: (ctx.videoMeta.width * desktopPreview.scale).toString() + "px"
                                                }
                                              }),
                                          className: "flex-1 flex items-center justify-center min-h-0 p-4"
                                        }),
                                    JsxRuntime.jsx("div", {
                                          children: Core__Option.getOr(Belt_Option.map(UseEditorLayout.calculateTimelineSize(rightPanelViewport, desktopPreview), (function (sectionSize) {
                                                      return JsxRuntime.jsx("div", {
                                                                  children: JsxRuntime.jsx(Timeline.make, {
                                                                        sectionSize: sectionSize
                                                                      }),
                                                                  className: "shadow-lg w-full bg-zinc-800",
                                                                  style: UseEditorLayout.sizeToStyle(sectionSize)
                                                                });
                                                    })), null),
                                          className: "shrink-0"
                                        })
                                  ],
                                  className: "flex-1 flex flex-col min-h-0 overflow-hidden bg-zinc-950"
                                })
                          ],
                          className: "flex flex-1 min-h-0 overflow-hidden"
                        }),
                    JsxRuntime.jsx(Dock.make, {
                          subtitlesManager: subtitlesManager,
                          render: render,
                          fullScreenToggler: fullScreenToggler,
                          videoFileName: videoFileName
                        })
                  ],
                  className: "w-screen h-screen bg-zinc-950 overflow-hidden flex flex-col",
                  id: "fframes-editor"
                });
    });

export {
  a ,
  useIsMobile ,
  calcMobilePreviewScale ,
  MobileSeekSlider ,
  MobileCanvasStyle ,
  SaveStatusBadge ,
  make$1 as make,
}
/*  Not a pure module */
