// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EditorContext from "./EditorContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SubtitleOctopusPreview from "./SubtitleOctopusPreview";

var make = SubtitleOctopusPreview.SubtitleOctopusPreview;

var Preview = {
  make: make
};

var mergeStyleWithMeta = (function(style, videoWidth, videoHeight) {
    return Object.assign({}, style, { _videoWidth: videoWidth, _videoHeight: videoHeight });
  });

function SubtitleOctopusPreview$1(props) {
  var ctx = EditorContext.useEditorContext();
  var match = ctx.usePlayer();
  var match$1 = ctx.useStyle();
  var videoWidth = ctx.videoMeta.width;
  var videoHeight = ctx.videoMeta.height;
  var styleWithMeta = mergeStyleWithMeta(match$1[0], videoWidth, videoHeight);
  return JsxRuntime.jsx(make, {
              width: videoWidth,
              height: videoHeight,
              cues: props.cues,
              subtitleStyle: styleWithMeta,
              currentTime: match[0].ts
            });
}

var make$1 = SubtitleOctopusPreview$1;

export {
  Preview ,
  mergeStyleWithMeta ,
  make$1 as make,
}
/* make Not a pure module */
